name: flutter_tizen_app_prototype
description: flutter_tizen_app_prototype
publish_to: 'none'

version: 0.0.1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  video_player: ^2.4.2
  video_player_tizen: ^2.4.9

  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/































